INSERT INTO `bx_country` (`country`,`iso`,`iso3`,`numcode`,`meta_locale`) VALUES
('Afghanistan','AF','AFG','004','en'),
('Aland','AX','ALA','248','en'),
('Albania','AL','ALB','008','en'),
('Algeria','DZ','DZA','012','en'),
('American Samoa','AS','ASM','016','en'),
('Andorra','AD','AND','020','en'),
('Angola','AO','AGO','024','en'),
('Anguilla','AI','AIA','660','en'),
('Antarctica','AQ','ATA','010','en'),
('Antigua and Barbuda','AG','ATG','028','en'),
('Argentina','AR','ARG','032','en'),
('Armenia','AM','ARM','051','en'),
('Aruba','AW','ABW','533','en'),
('Australia','AU','AUS','036','en'),
('Austria','AT','AUT','040','en'),
('Azerbaijan','AZ','AZE','031','en'),
('Bahamas','BS','BHS','044','en'),
('Bahrain','BH','BHR','048','en'),
('Bangladesh','BD','BGD','050','en'),
('Barbados','BB','BRB','052','en'),
('Belarus','BY','BLR','112','en'),
('Belgium','BE','BEL','056','en'),
('Belize','BZ','BLZ','084','en'),
('Benin','BJ','BEN','204','en'),
('Bermuda','BM','BMU','060','en'),
('Bhutan','BT','BTN','064','en'),
('Bolivia','BO','BOL','068','en'),
('Bosnia and Herzegovina','BA','BIH','070','en'),
('Botswana','BW','BWA','072','en'),
('Bouvet Island','BV','BVT','074','en'),
('Brazil','BR','BRA','076','en'),
('British Indian Ocean Territory','IO','IOT','086','en'),
('Brunei Darussalam','BN','BRN','096','en'),
('Bulgaria','BG','BGR','100','en'),
('Burkina Faso','BF','BFA','854','en'),
('Burundi','BI','BDI','108','en'),
('Cambodia','KH','KHM','116','en'),
('Cameroon','CM','CMR','120','en'),
('Canada','CA','CAN','124','en'),
('Cape Verde','CV','CPV','132','en'),
('Cayman Islands','KY','CYM','136','en'),
('Central African Republic','CF','CAF','140','en'),
('Chad','TD','TCD','148','en'),
('Chile','CL','CHL','152','en'),
('China','CN','CHN','156','en'),
('Christmas Island','CX','CXR','162','en'),
('Cocos (Keeling) Islands','CC','CCK','166','en'),
('Colombia','CO','COL','170','en'),
('Comoros','KM','COM','174','en'),
('Congo (Brazzaville)','CG','COG','178','en'),
('Congo (Kinshasa)','CD','COD','180','en'),
('Cook Islands','CK','COK','184','en'),
('Costa Rica','CR','CRI','188','en'),
('Cote d\'Ivoire','CI','CIV','384','en'),
('Croatia','HR','HRV','191','en'),
('Cuba','CU','CUB','192','en'),
('Cyprus','CY','CYP','196','en'),
('Czech Republic','CZ','CZE','203','en'),
('Denmark','DK','DNK','208','en'),
('Djibouti','DJ','DJI','262','en'),
('Dominica','DM','DMA','212','en'),
('Dominican Republic','DO','DOM','214','en'),
('Ecuador','EC','ECU','218','en'),
('Egypt','EG','EGY','818','en'),
('El Salvador','SV','SLV','222','en'),
('Equatorial Guinea','GQ','GNQ','226','en'),
('Eritrea','ER','ERI','232','en'),
('Estonia','EE','EST','233','en'),
('Ethiopia','ET','ETH','231','en'),
('European Union','EU',NULL,NULL,'en'),
('Falkland Islands','FK','FLK','238','en'),
('Faroe Islands','FO','FRO','234','en'),
('Fiji','FJ','FJI','242','en'),
('Finland','FI','FIN','246','en'),
('France','FR','FRA','250','en'),
('French Guiana','GF','GUF','254','en'),
('French Polynesia','PF','PYF','258','en'),
('French Southern Lands','TF','ATF','260','en'),
('Gabon','GA','GAB','266','en'),
('Gambia','GM','GMB','270','en'),
('Georgia','GE','GEO','268','en'),
('Germany','DE','DEU','276','en'),
('Ghana','GH','GHA','288','en'),
('Gibraltar','GI','GIB','292','en'),
('Greece','GR','GRC','300','en'),
('Greenland','GL','GRL','304','en'),
('Grenada','GD','GRD','308','en'),
('Guadeloupe','GP','GLP','312','en'),
('Guam','GU','GUM','316','en'),
('Guatemala','GT','GTM','320','en'),
('Guernsey','GG','GGY','831','en'),
('Guinea','GN','GIN','324','en'),
('Guinea-Bissau','GW','GNB','624','en'),
('Guyana','GY','GUY','328','en'),
('Haiti','HT','HTI','332','en'),
('Heard and McDonald Islands','HM','HMD','334','en'),
('Honduras','HN','HND','340','en'),
('Hong Kong','HK','HKG','344','en'),
('Hungary','HU','HUN','348','en'),
('Iceland','IS','ISL','352','en'),
('India','IN','IND','356','en'),
('Indonesia','ID','IDN','360','en'),
('Iran','IR','IRN','364','en'),
('Iraq','IQ','IRQ','368','en'),
('Ireland','IE','IRL','372','en'),
('Isle of Man','IM','IMN','833','en'),
('Israel','IL','ISR','376','en'),
('Italy','IT','ITA','380','en'),
('Jamaica','JM','JAM','388','en'),
('Japan','JP','JPN','392','en'),
('Jersey','JE','JEY','832','en'),
('Jordan','JO','JOR','400','en'),
('Kazakhstan','KZ','KAZ','398','en'),
('Kenya','KE','KEN','404','en'),
('Kiribati','KI','KIR','296','en'),
('Korea, North','KP','PRK','408','en'),
('Korea, South','KR','KOR','410','en'),
('Kuwait','KW','KWT','414','en'),
('Kyrgyzstan','KG','KGZ','417','en'),
('Laos','LA','LAO','418','en'),
('Latvia','LV','LVA','428','en'),
('Lebanon','LB','LBN','422','en'),
('Lesotho','LS','LSO','426','en'),
('Liberia','LR','LBR','430','en'),
('Libya','LY','LBY','434','en'),
('Liechtenstein','LI','LIE','438','en'),
('Lithuania','LT','LTU','440','en'),
('Luxembourg','LU','LUX','442','en'),
('Macau','MO','MAC','446','en'),
('Macedonia','MK','MKD','807','en'),
('Madagascar','MG','MDG','450','en'),
('Malawi','MW','MWI','454','en'),
('Malaysia','MY','MYS','458','en'),
('Maldives','MV','MDV','462','en'),
('Mali','ML','MLI','466','en'),
('Malta','MT','MLT','470','en'),
('Marshall Islands','MH','MHL','584','en'),
('Martinique','MQ','MTQ','474','en'),
('Mauritania','MR','MRT','478','en'),
('Mauritius','MU','MUS','480','en'),
('Mayotte','YT','MYT','175','en'),
('Mexico','MX','MEX','484','en'),
('Micronesia','FM','FSM','583','en'),
('Moldova','MD','MDA','498','en'),
('Monaco','MC','MCO','492','en'),
('Mongolia','MN','MNG','496','en'),
('Montenegro','ME','MNE','499','en'),
('Montserrat','MS','MSR','500','en'),
('Morocco','MA','MAR','504','en'),
('Mozambique','MZ','MOZ','508','en'),
('Myanmar','MM','MMR','104','en'),
('Namibia','NA','NAM','516','en'),
('Nauru','NR','NRU','520','en'),
('Nepal','NP','NPL','524','en'),
('Netherlands','NL','NLD','528','en'),
('Netherlands Antilles','AN','ANT','530','en'),
('New Caledonia','NC','NCL','540','en'),
('New Zealand','NZ','NZL','554','en'),
('Nicaragua','NI','NIC','558','en'),
('Niger','NE','NER','562','en'),
('Nigeria','NG','NGA','566','en'),
('Niue','NU','NIU','570','en'),
('Norfolk Island','NF','NFK','574','en'),
('Northern Mariana Islands','MP','MNP','580','en'),
('Norway','NO','NOR','578','en'),
('Oman','OM','OMN','512','en'),
('Pakistan','PK','PAK','586','en'),
('Palau','PW','PLW','585','en'),
('Palestine','PS','PSE','275','en'),
('Panama','PA','PAN','591','en'),
('Papua New Guinea','PG','PNG','598','en'),
('Paraguay','PY','PRY','600','en'),
('Peru','PE','PER','604','en'),
('Philippines','PH','PHL','608','en'),
('Pitcairn','PN','PCN','612','en'),
('Poland','PL','POL','616','en'),
('Portugal','PT','PRT','620','en'),
('Puerto Rico','PR','PRI','630','en'),
('Qatar','QA','QAT','634','en'),
('Reunion','RE','REU','638','en'),
('Romania','RO','ROU','642','en'),
('Russian Federation','RU','RUS','643','en'),
('Rwanda','RW','RWA','646','en'),
('Saint Barthelemy','BL','BLM','652','en'),
('Saint Helena','SH','SHN','654','en'),
('Saint Kitts and Nevis','KN','KNA','659','en'),
('Saint Lucia','LC','LCA','662','en'),
('Saint Martin (French part)','MF','MAF','663','en'),
('Saint Pierre and Miquelon','PM','SPM','666','en'),
('Saint Vincent and the Grenadines','VC','VCT','670','en'),
('Samoa','WS','WSM','882','en'),
('San Marino','SM','SMR','674','en'),
('Sao Tome and Principe','ST','STP','678','en'),
('Saudi Arabia','SA','SAU','682','en'),
('Senegal','SN','SEN','686','en'),
('Serbia','RS','SRB','688','en'),
('Seychelles','SC','SYC','690','en'),
('Sierra Leone','SL','SLE','694','en'),
('Singapore','SG','SGP','702','en'),
('Slovakia','SK','SVK','703','en'),
('Slovenia','SI','SVN','705','en'),
('Solomon Islands','SB','SLB','090','en'),
('Somalia','SO','SOM','706','en'),
('South Africa','ZA','ZAF','710','en'),
('Spain','ES','ESP','724','en'),
('Sri Lanka','LK','LKA','144','en'),
('Sudan','SD','SDN','736','en'),
('Suriname','SR','SUR','740','en'),
('Svalbard and Jan Mayen Islands','SJ','SJM','744','en'),
('Swaziland','SZ','SWZ','748','en'),
('Sweden','SE','SWE','752','en'),
('Switzerland','CH','CHE','756','en'),
('Syria','SY','SYR','760','en'),
('Taiwan','TW','TWN','158','en'),
('Tajikistan','TJ','TJK','762','en'),
('Tanzania','TZ','TZA','834','en'),
('Thailand','TH','THA','764','en'),
('Timor-Leste','TL','TLS','626','en'),
('Togo','TG','TGO','768','en'),
('Tokelau','TK','TKL','772','en'),
('Tonga','TO','TON','776','en'),
('Trinidad and Tobago','TT','TTO','780','en'),
('Tunisia','TN','TUN','788','en'),
('Turkey','TR','TUR','792','en'),
('Turkmenistan','TM','TKM','795','en'),
('Turks and Caicos Islands','TC','TCA','796','en'),
('Tuvalu','TV','TUV','798','en'),
('Uganda','UG','UGA','800','en'),
('Ukraine','UA','UKR','804','en'),
('United Arab Emirates','AE','ARE','784','en'),
('United Kingdom','GB','GBR','826','en'),
('United States Minor Outlying Islands','UM','UMI','581','en'),
('United States of America','US','USA','840','en'),
('Uruguay','UY','URY','858','en'),
('Uzbekistan','UZ','UZB','860','en'),
('Vanuatu','VU','VUT','548','en'),
('Vatican City','VA','VAT','336','en'),
('Venezuela','VE','VEN','862','en'),
('Vietnam','VN','VNM','704','en'),
('Virgin Islands, British','VG','VGB','092','en'),
('Virgin Islands, U.S.','VI','VIR','850','en'),
('Wallis and Futuna Islands','WF','WLF','876','en'),
('Western Sahara','EH','ESH','732','en'),
('Yemen','YE','YEM','887','en'),
('Zambia','ZM','ZMB','894','en'),
('Zimbabwe','ZW','ZWE','716','en');

# ('South Georgia and South Sandwich Islands','GS','SGS','239','en'),